export interface TierPokemon {
  id: number
  name: string
  types: string[]
}

export interface TierData {
  name: string
  description: string
  color: string
  pokemon: TierPokemon[]
}

export const TIER_DATA: Record<string, TierData> = {
  S: {
    name: "S Tier",
    description:
      "S Tier Pokémon are the strongest, most versatile, and most useful Pokémon you can power up. These Pokémon consistently serve as the best counters across a wide variety of raid bosses, making them worthy of your Stardust and Candy investment.",
    color: "bg-green-600",
    pokemon: [
      { id: 383, name: "Primal Groudon", types: ["ground", "fire"] },
      { id: 384, name: "Mega Rayquaza", types: ["dragon", "flying"] },
      { id: 890, name: "Eternatus", types: ["poison", "dragon"] },
      { id: 150, name: "Shadow Mewtwo", types: ["psychic"] },
      { id: 646, name: "Black Kyurem", types: ["dragon", "ice"] },
      { id: 382, name: "Primal Kyogre", types: ["water"] },
      { id: 373, name: "Shadow Salamence", types: ["dragon", "flying"] },
      { id: 800, name: "Dawn Wings Necrozma", types: ["psychic", "ghost"] },
      { id: 888, name: "Crowned Sword Zacian", types: ["fairy", "steel"] },
      { id: 257, name: "Mega Blaziken", types: ["fire", "fighting"] },
      { id: 646, name: "White Kyurem", types: ["dragon", "ice"] },
      { id: 448, name: "Mega Lucario", types: ["fighting", "steel"] },
      { id: 464, name: "Shadow Rhyperior", types: ["ground", "rock"] },
      { id: 445, name: "Mega Garchomp", types: ["dragon", "ground"] },
      { id: 373, name: "Mega Salamence", types: ["dragon", "flying"] },
      { id: 609, name: "Shadow Chandelure", types: ["ghost", "fire"] },
      { id: 486, name: "Shadow Regigigas", types: ["normal"] },
      { id: 381, name: "Mega Latios", types: ["dragon", "psychic"] },
      { id: 282, name: "Mega Gardevoir", types: ["psychic", "fairy"] },
      { id: 248, name: "Mega Tyranitar", types: ["rock", "dark"] },
    ],
  },
  "A+": {
    name: "A+ Tier",
    description:
      "A+ Tier Pokémon are amazing attackers and frequently strong counters, often comparable to S Tier. They are powerful, versatile, and dependable Pokémon that are definitely worth powering up, even though they may not be quite as reliable or as versatile as S Tier.",
    color: "bg-green-500",
    pokemon: [
      { id: 243, name: "Shadow Raikou", types: ["electric"] },
      { id: 800, name: "Dusk Mane Necrozma", types: ["psychic", "steel"] },
      { id: 94, name: "Mega Gengar", types: ["ghost", "poison"] },
      { id: 445, name: "Shadow Garchomp", types: ["dragon", "ground"] },
      { id: 889, name: "Crowned Shield Zamazenta", types: ["fighting", "steel"] },
      { id: 473, name: "Shadow Mamoswine", types: ["ice", "ground"] },
      { id: 248, name: "Shadow Tyranitar", types: ["rock", "dark"] },
      { id: 214, name: "Mega Heracross", types: ["bug", "fighting"] },
      { id: 384, name: "Rayquaza", types: ["dragon", "flying"] },
      { id: 383, name: "Shadow Groudon", types: ["ground"] },
      { id: 475, name: "Mega Gallade", types: ["psychic", "fighting"] },
      { id: 6, name: "Mega Charizard Y", types: ["fire", "flying"] },
      { id: 257, name: "Shadow Blaziken", types: ["fire", "fighting"] },
      { id: 530, name: "Shadow Excadrill", types: ["ground", "steel"] },
      { id: 146, name: "Shadow Moltres", types: ["fire", "flying"] },
      { id: 719, name: "Mega Diancie", types: ["rock", "fairy"] },
      { id: 376, name: "Shadow Metagross", types: ["steel", "psychic"] },
      { id: 65, name: "Mega Alakazam", types: ["psychic"] },
      { id: 639, name: "Terrakion", types: ["rock", "fighting"] },
      { id: 485, name: "Shadow Heatran", types: ["fire", "steel"] },
      { id: 409, name: "Shadow Rampardos", types: ["rock"] },
      { id: 254, name: "Mega Sceptile", types: ["grass", "dragon"] },
      { id: 381, name: "Shadow Latios", types: ["dragon", "psychic"] },
      { id: 260, name: "Mega Swampert", types: ["water", "ground"] },
      { id: 145, name: "Shadow Zapdos", types: ["electric", "flying"] },
      { id: 738, name: "Shadow Vikavolt", types: ["bug", "electric"] },
      { id: 645, name: "Therian Forme Landorus", types: ["ground", "flying"] },
      { id: 806, name: "Blacephalon", types: ["fire", "ghost"] },
      { id: 461, name: "Shadow Weavile", types: ["dark", "ice"] },
      { id: 500, name: "Shadow Emboar", types: ["fire", "fighting"] },
    ],
  },
  A: {
    name: "A Tier",
    description:
      "A Tier Pokémon are situational specialists and solid standard counters. These Pokémon exemplify the best among non-Shadow and non-Mega Pokémon, and are often the best counters for specific raid bosses.",
    color: "bg-lime-500",
    pokemon: [
      { id: 697, name: "Shadow Tyrantrum", types: ["rock", "dragon"] },
      { id: 796, name: "Xurkitree", types: ["electric"] },
      { id: 534, name: "Shadow Conkeldurr", types: ["fighting"] },
      { id: 555, name: "Standard Mode Shadow Darmanitan", types: ["fire"] },
      { id: 894, name: "Regieleki", types: ["electric"] },
      { id: 448, name: "Lucario", types: ["fighting", "steel"] },
      { id: 643, name: "Reshiram", types: ["dragon", "fire"] },
      { id: 229, name: "Mega Houndoom", types: ["dark", "fire"] },
      { id: 250, name: "Apex Shadow Ho-Oh", types: ["fire", "flying"] },
      { id: 635, name: "Shadow Hydreigon", types: ["dark", "dragon"] },
      { id: 483, name: "Shadow Dialga", types: ["steel", "dragon"] },
      { id: 150, name: "Mewtwo", types: ["psychic"] },
      { id: 644, name: "Zekrom", types: ["dragon", "electric"] },
      { id: 250, name: "Shadow Ho-Oh", types: ["fire", "flying"] },
      { id: 466, name: "Shadow Electivire", types: ["electric"] },
      { id: 382, name: "Shadow Kyogre", types: ["water"] },
      { id: 526, name: "Shadow Gigalith", types: ["rock"] },
      { id: 798, name: "Kartana", types: ["grass", "steel"] },
      { id: 6, name: "Mega Charizard X", types: ["fire", "dragon"] },
      { id: 380, name: "Mega Latias", types: ["dragon", "psychic"] },
      { id: 642, name: "Therian Forme Thundurus", types: ["electric", "flying"] },
      { id: 462, name: "Shadow Magnezone", types: ["electric", "steel"] },
      { id: 398, name: "Shadow Staraptor", types: ["normal", "flying"] },
      { id: 142, name: "Mega Aerodactyl", types: ["rock", "flying"] },
      { id: 359, name: "Mega Absol", types: ["dark"] },
      { id: 310, name: "Mega Manectric", types: ["electric"] },
      { id: 68, name: "Shadow Machamp", types: ["fighting"] },
      { id: 6, name: "Shadow Charizard", types: ["fire", "flying"] },
      { id: 905, name: "Incarnate Forme Enamorus", types: ["fairy", "flying"] },
      { id: 244, name: "Shadow Entei", types: ["fire"] },
      { id: 383, name: "Groudon", types: ["ground"] },
      { id: 647, name: "Keldeo (Resolute Forme)", types: ["water", "fighting"] },
      { id: 130, name: "Mega Gyarados", types: ["water", "dark"] },
      { id: 647, name: "Keldeo (Ordinary Forme)", types: ["water", "fighting"] },
      { id: 464, name: "Rhyperior", types: ["ground", "rock"] },
      { id: 282, name: "Shadow Gardevoir", types: ["psychic", "fairy"] },
      { id: 792, name: "Lunala", types: ["psychic", "ghost"] },
      { id: 430, name: "Shadow Honchkrow", types: ["dark", "flying"] },
      { id: 354, name: "Mega Banette", types: ["ghost"] },
      { id: 373, name: "Salamence", types: ["dragon", "flying"] },
      { id: 297, name: "Shadow Hariyama", types: ["fighting"] },
      { id: 484, name: "Shadow Palkia", types: ["water", "dragon"] },
      { id: 492, name: "Sky Forme Shaymin", types: ["grass", "flying"] },
      { id: 94, name: "Shadow Gengar", types: ["ghost", "poison"] },
      { id: 389, name: "Shadow Torterra", types: ["grass", "ground"] },
      { id: 181, name: "Mega Ampharos", types: ["electric", "dragon"] },
      { id: 609, name: "Chandelure", types: ["ghost", "fire"] },
      { id: 3, name: "Mega Venusaur", types: ["grass", "poison"] },
      { id: 254, name: "Shadow Sceptile", types: ["grass"] },
      { id: 720, name: "Hoopa Unbound", types: ["psychic", "dark"] },
    ],
  },
  "B+": {
    name: "B+ Tier",
    description:
      "B+ Tier Pokémon are solid attackers that can serve as good counters in many situations. While they may not be the absolute best, they are reliable options worth considering for your team.",
    color: "bg-orange-500",
    pokemon: [
      { id: 9, name: "Mega Blastoise", types: ["water"] },
      { id: 260, name: "Shadow Swampert", types: ["water", "ground"] },
      { id: 65, name: "Shadow Alakazam", types: ["psychic"] },
      { id: 445, name: "Garchomp", types: ["dragon", "ground"] },
      { id: 359, name: "Shadow Absol", types: ["dark"] },
      { id: 392, name: "Shadow Infernape", types: ["fire", "fighting"] },
      { id: 465, name: "Shadow Tangrowth", types: ["grass"] },
      { id: 3, name: "Shadow Venusaur", types: ["grass", "poison"] },
      { id: 157, name: "Shadow Typhlosion", types: ["fire"] },
      { id: 483, name: "Origin Forme Dialga", types: ["steel", "dragon"] },
      { id: 15, name: "Mega Beedrill", types: ["bug", "poison"] },
      { id: 717, name: "Yveltal", types: ["dark", "flying"] },
      { id: 409, name: "Rampardos", types: ["rock"] },
      { id: 76, name: "Shadow Alolan Golem", types: ["rock", "electric"] },
      { id: 637, name: "Volcarona", types: ["bug", "fire"] },
      { id: 99, name: "Shadow Kingler", types: ["water"] },
      { id: 248, name: "Tyranitar", types: ["rock", "dark"] },
      { id: 893, name: "Zarude", types: ["dark", "grass"] },
      { id: 405, name: "Shadow Luxray", types: ["electric"] },
      { id: 103, name: "Shadow Exeggutor", types: ["grass", "psychic"] },
      { id: 473, name: "Mamoswine", types: ["ice", "ground"] },
      { id: 243, name: "Raikou", types: ["electric"] },
      { id: 376, name: "Metagross", types: ["steel", "psychic"] },
      { id: 892, name: "Urshifu (Rapid Strike Style)", types: ["fighting", "water"] },
      { id: 127, name: "Mega Pinsir", types: ["bug", "flying"] },
      { id: 623, name: "Shadow Golurk", types: ["ground", "ghost"] },
      { id: 428, name: "Mega Lopunny", types: ["normal", "fighting"] },
      { id: 491, name: "Darkrai", types: ["dark"] },
      { id: 18, name: "Mega Pidgeot", types: ["normal", "flying"] },
      { id: 699, name: "Shadow Aurorus", types: ["rock", "ice"] },
      { id: 892, name: "Urshifu (Single Strike Style)", types: ["fighting", "dark"] },
      { id: 530, name: "Excadrill", types: ["ground", "steel"] },
      { id: 112, name: "Shadow Rhydon", types: ["ground", "rock"] },
      { id: 380, name: "Shadow Latias", types: ["dragon", "psychic"] },
      { id: 76, name: "Shadow Golem", types: ["rock", "ground"] },
      { id: 467, name: "Shadow Magmortar", types: ["fire"] },
      { id: 795, name: "Pheromosa", types: ["bug", "fighting"] },
      { id: 503, name: "Shadow Samurott", types: ["water"] },
      { id: 382, name: "Kyogre", types: ["water"] },
      { id: 407, name: "Roserade", types: ["grass", "poison"] },
      { id: 887, name: "Dragapult", types: ["dragon", "ghost"] },
      { id: 645, name: "Incarnate Forme Landorus", types: ["ground", "flying"] },
      { id: 395, name: "Shadow Empoleon", types: ["water", "steel"] },
      { id: 229, name: "Shadow Houndoom", types: ["dark", "fire"] },
      { id: 865, name: "Shadow Sirfetch'd", types: ["fighting"] },
      { id: 998, name: "Baxcalibur", types: ["dragon", "ice"] },
      { id: 475, name: "Shadow Gallade", types: ["psychic", "fighting"] },
      { id: 635, name: "Hydreigon", types: ["dark", "dragon"] },
      { id: 149, name: "Shadow Dragonite", types: ["dragon", "flying"] },
      { id: 484, name: "Origin Forme Palkia", types: ["water", "dragon"] },
    ],
  },
  B: {
    name: "B Tier",
    description:
      "B Tier Pokémon are decent attackers that can fill specific roles. While there are often better options available, these Pokémon can still be useful in certain situations.",
    color: "bg-orange-600",
    pokemon: [
      { id: 454, name: "Shadow Toxicroak", types: ["poison", "fighting"] },
      { id: 306, name: "Shadow Aggron", types: ["steel", "rock"] },
      { id: 567, name: "Shadow Archeops", types: ["rock", "flying"] },
      { id: 212, name: "Mega Scizor", types: ["bug", "steel"] },
      { id: 483, name: "Dialga", types: ["steel", "dragon"] },
      { id: 474, name: "Shadow Porygon-Z", types: ["normal"] },
      { id: 103, name: "Shadow Alolan Exeggutor", types: ["grass", "dragon"] },
      { id: 232, name: "Shadow Donphan", types: ["ground"] },
      { id: 160, name: "Shadow Feraligatr", types: ["water"] },
      { id: 466, name: "Electivire", types: ["electric"] },
      { id: 212, name: "Shadow Scizor", types: ["bug", "steel"] },
      { id: 286, name: "Breloom", types: ["grass", "fighting"] },
      { id: 144, name: "Galarian Articuno", types: ["psychic", "flying"] },
      { id: 697, name: "Tyrantrum", types: ["rock", "dragon"] },
      { id: 450, name: "Shadow Hippowdon", types: ["ground"] },
      { id: 130, name: "Shadow Gyarados", types: ["water", "flying"] },
      { id: 786, name: "Tapu Lele", types: ["psychic", "fairy"] },
      { id: 787, name: "Tapu Bulu", types: ["grass", "fairy"] },
      { id: 555, name: "Galarian Standard Mode Darmanitan", types: ["ice"] },
      { id: 146, name: "Moltres", types: ["fire", "flying"] },
      { id: 904, name: "Shadow Overqwil", types: ["dark", "poison"] },
      { id: 534, name: "Conkeldurr", types: ["fighting"] },
      { id: 249, name: "Apex Shadow Lugia", types: ["psychic", "flying"] },
      { id: 142, name: "Shadow Aerodactyl", types: ["rock", "flying"] },
      { id: 460, name: "Mega Abomasnow", types: ["grass", "ice"] },
      { id: 866, name: "Shadow Mr. Rime", types: ["ice", "psychic"] },
      { id: 310, name: "Shadow Manectric", types: ["electric"] },
      { id: 1000, name: "Gholdengo", types: ["steel", "ghost"] },
      { id: 979, name: "Shadow Annihilape", types: ["fighting", "ghost"] },
      { id: 257, name: "Blaziken", types: ["fire", "fighting"] },
      { id: 903, name: "Shadow Sneasler", types: ["fighting", "poison"] },
      { id: 908, name: "Meowscarada", types: ["grass", "dark"] },
      { id: 485, name: "Heatran", types: ["fire", "steel"] },
      { id: 71, name: "Shadow Victreebel", types: ["grass", "poison"] },
      { id: 802, name: "Marshadow", types: ["fighting", "ghost"] },
      { id: 720, name: "Hoopa Confined", types: ["psychic", "ghost"] },
      { id: 812, name: "Rillaboom", types: ["grass"] },
      { id: 461, name: "Weavile", types: ["dark", "ice"] },
      { id: 793, name: "Nihilego", types: ["rock", "poison"] },
      { id: 785, name: "Tapu Koko", types: ["electric", "fairy"] },
      { id: 342, name: "Shadow Crawdaunt", types: ["water", "dark"] },
      { id: 804, name: "Naganadel", types: ["poison", "dragon"] },
      { id: 362, name: "Mega Glalie", types: ["ice"] },
      { id: 555, name: "Standard Mode Darmanitan", types: ["fire"] },
      { id: 59, name: "Shadow Arcanine", types: ["fire"] },
      { id: 330, name: "Shadow Flygon", types: ["ground", "dragon"] },
      { id: 895, name: "Regidrago", types: ["dragon"] },
      { id: 306, name: "Mega Aggron", types: ["steel"] },
      { id: 555, name: "Darmanitan", types: ["fire"] },
      { id: 462, name: "Magnezone", types: ["electric", "steel"] },
    ],
  },
  C: {
    name: "C Tier",
    description:
      "C Tier Pokémon are situational options that can work in specific scenarios. While they may not be the most efficient choices, they can still contribute to your team when needed.",
    color: "bg-red-500",
    pokemon: [
      { id: 649, name: "Genesect (Chill Drive)", types: ["bug", "steel"] },
      { id: 145, name: "Zapdos", types: ["electric", "flying"] },
      { id: 144, name: "Shadow Articuno", types: ["ice", "flying"] },
      { id: 526, name: "Gigalith", types: ["rock"] },
      { id: 649, name: "Genesect (Shock Drive)", types: ["bug", "steel"] },
      { id: 381, name: "Latios", types: ["dragon", "psychic"] },
      { id: 730, name: "Primarina", types: ["water", "fairy"] },
      { id: 646, name: "Kyurem", types: ["dragon", "ice"] },
      { id: 487, name: "Shadow Giratina (Altered Forme)", types: ["ghost", "dragon"] },
      { id: 649, name: "Genesect", types: ["bug", "steel"] },
      { id: 471, name: "Glaceon", types: ["ice"] },
      { id: 319, name: "Mega Sharpedo", types: ["water", "dark"] },
      { id: 521, name: "Shadow Unfezant", types: ["normal", "flying"] },
      { id: 398, name: "Staraptor", types: ["normal", "flying"] },
      { id: 724, name: "Decidueye", types: ["grass", "ghost"] },
      { id: 612, name: "Haxorus", types: ["dragon"] },
      { id: 359, name: "Absol", types: ["dark"] },
      { id: 649, name: "Genesect (Douse Drive)", types: ["bug", "steel"] },
      { id: 487, name: "Giratina (Origin Forme)", types: ["ghost", "dragon"] },
      { id: 914, name: "Quaquaval", types: ["water", "fighting"] },
      { id: 901, name: "Shadow Ursaluna", types: ["ground", "normal"] },
      { id: 724, name: "Hisuian Decidueye", types: ["grass", "fighting"] },
      { id: 139, name: "Shadow Omastar", types: ["rock", "water"] },
      { id: 975, name: "Cetitan", types: ["ice"] },
      { id: 127, name: "Shadow Pinsir", types: ["bug"] },
      { id: 983, name: "Kingambit", types: ["dark", "steel"] },
      { id: 68, name: "Machamp", types: ["fighting"] },
      { id: 145, name: "Galarian Zapdos", types: ["fighting", "flying"] },
      { id: 486, name: "Regigigas", types: ["normal"] },
      { id: 249, name: "Shadow Lugia", types: ["psychic", "flying"] },
      { id: 82, name: "Shadow Magneton", types: ["electric", "steel"] },
      { id: 649, name: "Genesect (Burn Drive)", types: ["bug", "steel"] },
      { id: 484, name: "Palkia", types: ["water", "dragon"] },
      { id: 94, name: "Gengar", types: ["ghost", "poison"] },
      { id: 699, name: "Aurorus", types: ["rock", "ice"] },
      { id: 658, name: "Greninja", types: ["water", "dark"] },
      { id: 558, name: "Shadow Crustle", types: ["bug", "rock"] },
      { id: 652, name: "Chesnaught", types: ["grass", "fighting"] },
      { id: 727, name: "Incineroar", types: ["fire", "dark"] },
      { id: 45, name: "Shadow Vileplume", types: ["grass", "poison"] },
      { id: 539, name: "Shadow Sawk", types: ["fighting"] },
      { id: 589, name: "Shadow Escavalier", types: ["bug", "steel"] },
      { id: 99, name: "Kingler", types: ["water"] },
      { id: 545, name: "Shadow Scolipede", types: ["bug", "poison"] },
      { id: 523, name: "Shadow Zebstrika", types: ["electric"] },
      { id: 34, name: "Shadow Nidoking", types: ["poison", "ground"] },
      { id: 874, name: "Stonjourner", types: ["rock"] },
      { id: 154, name: "Shadow Meganium", types: ["grass"] },
      { id: 655, name: "Delphox", types: ["fire", "psychic"] },
      { id: 641, name: "Therian Forme Tornadus", types: ["flying"] },
    ],
  },
  D: {
    name: "D Tier",
    description:
      "D Tier Pokémon are niche options that have limited use cases. While they may occasionally be useful, there are almost always better alternatives available for most situations.",
    color: "bg-red-600",
    pokemon: [
      { id: 332, name: "Shadow Cacturne", types: ["grass", "dark"] },
      { id: 38, name: "Shadow Alolan Ninetales", types: ["ice", "fairy"] },
      { id: 553, name: "Krookodile", types: ["ground", "dark"] },
      { id: 763, name: "Tsareena", types: ["grass"] },
      { id: 254, name: "Sceptile", types: ["grass"] },
      { id: 65, name: "Alakazam", types: ["psychic"] },
      { id: 460, name: "Shadow Abomasnow", types: ["grass", "ice"] },
      { id: 275, name: "Shadow Shiftry", types: ["grass", "dark"] },
      { id: 378, name: "Shadow Regice", types: ["ice"] },
      { id: 584, name: "Vanilluxe", types: ["ice"] },
      { id: 365, name: "Shadow Walrein", types: ["ice", "water"] },
      { id: 623, name: "Golurk", types: ["ground", "ghost"] },
      { id: 716, name: "Xerneas", types: ["fairy"] },
      { id: 112, name: "Rhydon", types: ["ground", "rock"] },
      { id: 571, name: "Hisuian Zoroark", types: ["normal", "ghost"] },
      { id: 713, name: "Avalugg", types: ["ice"] },
      { id: 91, name: "Shadow Cloyster", types: ["water", "ice"] },
      { id: 297, name: "Hariyama", types: ["fighting"] },
      { id: 31, name: "Shadow Nidoqueen", types: ["poison", "ground"] },
      { id: 721, name: "Volcanion", types: ["fire", "water"] },
      { id: 809, name: "Melmetal", types: ["steel"] },
      { id: 794, name: "Buzzwole", types: ["bug", "fighting"] },
      { id: 196, name: "Espeon", types: ["psychic"] },
      { id: 465, name: "Tangrowth", types: ["grass"] },
      { id: 866, name: "Mr. Rime", types: ["ice", "psychic"] },
      { id: 210, name: "Shadow Granbull", types: ["fairy"] },
      { id: 123, name: "Shadow Scyther", types: ["bug", "flying"] },
      { id: 142, name: "Aerodactyl", types: ["rock", "flying"] },
      { id: 149, name: "Dragonite", types: ["dragon", "flying"] },
      { id: 3, name: "Venusaur", types: ["grass", "poison"] },
      { id: 221, name: "Shadow Piloswine", types: ["ice", "ground"] },
      { id: 306, name: "Aggron", types: ["steel", "rock"] },
      { id: 500, name: "Emboar", types: ["fire", "fighting"] },
      { id: 377, name: "Shadow Regirock", types: ["rock"] },
      { id: 873, name: "Frosmoth", types: ["ice", "bug"] },
      { id: 638, name: "Cobalion", types: ["steel", "fighting"] },
      { id: 131, name: "Shadow Lapras", types: ["water", "ice"] },
      { id: 76, name: "Golem", types: ["rock", "ground"] },
      { id: 282, name: "Gardevoir", types: ["psychic", "fairy"] },
      { id: 260, name: "Swampert", types: ["water", "ground"] },
      { id: 472, name: "Shadow Gliscor", types: ["ground", "flying"] },
      { id: 144, name: "Articuno", types: ["ice", "flying"] },
      { id: 468, name: "Togekiss", types: ["fairy", "flying"] },
      { id: 745, name: "Lycanroc (Dusk Form)", types: ["rock"] },
      { id: 89, name: "Shadow Alolan Muk", types: ["poison", "dark"] },
      { id: 701, name: "Hawlucha", types: ["fighting", "flying"] },
      { id: 750, name: "Mudsdale", types: ["ground"] },
      { id: 888, name: "Zacian (Hero of Many Battles)", types: ["fairy"] },
      { id: 738, name: "Vikavolt", types: ["bug", "electric"] },
      { id: 185, name: "Shadow Sudowoodo", types: ["rock"] },
    ],
  },
}
