export interface TierPokemon {
  id: number
  name: string
  types: string[]
}

export interface TierData {
  name: string
  description: string
  color: string
  pokemon: TierPokemon[]
}

export const TIER_DATA: Record<string, TierData> = {
  S: {
    name: "S Tier",
    description:
      "S Tier Pokémon are the most dominant gym and raid defenders in Pokémon GO. With unmatched bulk and strong defensive typings, these Pokémon are incredibly difficult to defeat and form the backbone of any gym defense.",
    color: "bg-blue-600",
    pokemon: [
      { id: 242, name: "Blissey", types: ["normal"] },
      { id: 113, name: "Chansey", types: ["normal"] },
    ],
  },

  "A+": {
    name: "A+ Tier",
    description:
      "A+ Tier defenders are powerful and reliable walls that offer high stamina, resistance coverage, and defensive typing, making them excellent for gym placement and raid durability.",
    color: "bg-blue-500",
    pokemon: [
      { id: 143, name: "Gigantamax Snorlax", types: ["normal"] },
      { id: 143, name: "Snorlax", types: ["normal"] },
      { id: 197, name: "Umbreon", types: ["dark"] },
      { id: 713, name: "Avalugg", types: ["ice"] },
      { id: 713, name: "Hisuian Avalugg", types: ["ice", "rock"] },
      { id: 809, name: "Melmetal", types: ["steel"] },
      { id: 901, name: "Ursaluna", types: ["ground", "normal"] },
      { id: 706, name: "Goodra", types: ["dragon"] },
      { id: 630, name: "Mandibuzz", types: ["dark", "flying"] },
      { id: 208, name: "Steelix", types: ["steel", "ground"] },
      { id: 131, name: "Gigantamax Lapras", types: ["water", "ice"] },
      { id: 131, name: "Lapras", types: ["water", "ice"] },
      { id: 464, name: "Rhyperior", types: ["ground", "rock"] },
      { id: 350, name: "Milotic", types: ["water"] },
      { id: 289, name: "Slaking", types: ["normal"] },
      { id: 248, name: "Tyranitar", types: ["rock", "dark"] },
      { id: 445, name: "Garchomp", types: ["dragon", "ground"] },
      { id: 369, name: "Relicanth", types: ["water", "rock"] },
      { id: 983, name: "Kingambit", types: ["dark", "steel"] },
      { id: 450, name: "Hippowdon", types: ["ground"] },
      { id: 671, name: "Florges", types: ["fairy"] },
      { id: 134, name: "Vaporeon", types: ["water"] },
      { id: 411, name: "Bastiodon", types: ["rock", "steel"] },
    ],
  },

  A: {
    name: "A Tier",
    description:
      "A Tier defenders are dependable and bulky Pokémon that excel in gyms or PvE defense. They may not have the absolute best stats, but they’re durable and reliable.",
    color: "bg-sky-500",
    pokemon: [
      { id: 700, name: "Sylveon", types: ["fairy"] },
      { id: 594, name: "Alomomola", types: ["water"] },
      { id: 306, name: "Aggron", types: ["steel", "rock"] },
      { id: 463, name: "Lickilicky", types: ["normal"] },
      { id: 1017, name: "Hydrapple", types: ["grass", "dragon"] },
      { id: 784, name: "Kommo-o", types: ["dragon", "fighting"] },
      { id: 376, name: "Metagross", types: ["steel", "psychic"] },
      { id: 699, name: "Aurorus", types: ["rock", "ice"] },
      { id: 979, name: "Annihilape", types: ["fighting", "ghost"] },
      { id: 468, name: "Togekiss", types: ["fairy", "flying"] },
      { id: 975, name: "Cetitan", types: ["ice"] },
      { id: 476, name: "Probopass", types: ["rock", "steel"] },
      { id: 365, name: "Walrein", types: ["ice", "water"] },
      { id: 823, name: "Corviknight", types: ["flying", "steel"] },
      { id: 681, name: "Aegislash (Shield Forme)", types: ["steel", "ghost"] },
      { id: 518, name: "Musharna", types: ["psychic"] },
      { id: 980, name: "Clodsire", types: ["poison", "ground"] },
      { id: 241, name: "Miltank", types: ["normal"] },
      { id: 652, name: "Chesnaught", types: ["grass", "fighting"] },
      { id: 538, name: "Throh", types: ["fighting"] },
      { id: 615, name: "Cryogonal", types: ["ice"] },
      { id: 465, name: "Tangrowth", types: ["grass"] },
      { id: 149, name: "Dragonite", types: ["dragon", "flying"] },
      { id: 911, name: "Skeledirge", types: ["fire", "ghost"] },
      { id: 862, name: "Obstagoon", types: ["dark", "normal"] },
    ],
  },

  B: {
    name: "B Tier",
    description:
      "B Tier defenders are solid choices that may have specific weaknesses or limited versatility but still bring valuable durability and type resistance to gyms.",
    color: "bg-cyan-500",
    pokemon: [
      { id: 618, name: "Stunfisk", types: ["ground", "electric"] },
      { id: 618, name: "Galarian Stunfisk", types: ["ground", "steel"] },
      { id: 874, name: "Stonjourner", types: ["rock"] },
      { id: 768, name: "Golisopod", types: ["bug", "water"] },
      { id: 916, name: "Oinkologne (Female)", types: ["normal"] },
      { id: 389, name: "Torterra", types: ["grass", "ground"] },
      { id: 820, name: "Greedent", types: ["normal"] },
      { id: 202, name: "Wobbuffet", types: ["psychic"] },
      { id: 982, name: "Dudunsparce (Three-Segment Form)", types: ["normal"] },
      { id: 982, name: "Dudunsparce (Two-Segment Form)", types: ["normal"] },
      { id: 472, name: "Gliscor", types: ["ground", "flying"] },
      { id: 130, name: "Gyarados", types: ["water", "flying"] },
      { id: 89, name: "Muk", types: ["poison"] },
      { id: 89, name: "Alolan Muk", types: ["poison", "dark"] },
      { id: 89, name: "Shadow Alolan Muk", types: ["poison", "dark"] },
      { id: 593, name: "Jellicent", types: ["water", "ghost"] },
      { id: 346, name: "Cradily", types: ["rock", "grass"] },
      { id: 673, name: "Gogoat", types: ["grass"] },
      { id: 998, name: "Baxcalibur", types: ["dragon", "ice"] },
      { id: 115, name: "Kangaskhan", types: ["normal"] },
      { id: 154, name: "Meganium", types: ["grass"] },
      { id: 1000, name: "Gholdengo", types: ["steel", "ghost"] },
      { id: 62, name: "Poliwrath", types: ["water", "fighting"] },
      { id: 727, name: "Incineroar", types: ["fire", "dark"] },
      { id: 76, name: "Golem", types: ["rock", "ground"] },
      { id: 618, name: "Jellicent (Female)", types: ["water", "ghost"] },
      { id: 598, name: "Ferrothorn", types: ["grass", "steel"] },
      { id: 112, name: "Rhydon", types: ["ground", "rock"] },
      { id: 526, name: "Gigalith", types: ["rock"] },
      { id: 765, name: "Oranguru", types: ["normal", "psychic"] },
      { id: 73, name: "Tentacruel", types: ["water", "poison"] },
      { id: 918, name: "Toedscruel", types: ["ground", "grass"] },
      { id: 635, name: "Hydreigon", types: ["dark", "dragon"] },
      { id: 711, name: "Gourgeist (Super Size)", types: ["ghost", "grass"] },
      { id: 937, name: "Bellibolt", types: ["electric"] },
      { id: 260, name: "Swampert", types: ["water", "ground"] },
      { id: 626, name: "Bouffalant", types: ["normal"] },
      { id: 750, name: "Mudsdale", types: ["ground"] },
      { id: 326, name: "Grumpig", types: ["psychic"] },
      { id: 9, name: "Gigantamax Blastoise", types: ["water"] },
      { id: 9, name: "Blastoise", types: ["water"] },
      { id: 80, name: "Slowbro", types: ["water", "psychic"] },
      { id: 199, name: "Slowking", types: ["water", "psychic"] },
      { id: 199, name: "Galarian Slowking", types: ["poison", "psychic"] },
      { id: 1003, name: "Tinkaton", types: ["fairy", "steel"] },
      { id: 232, name: "Donphan", types: ["ground"] },
      { id: 97, name: "Hypno", types: ["psychic"] },
      { id: 812, name: "Gigantamax Rillaboom", types: ["grass"] },
      { id: 812, name: "Rillaboom", types: ["grass"] },
      { id: 76, name: "Alolan Golem", types: ["rock", "electric"] },
    ],
  },

  C: {
  name: "C Tier",
  description:
    "C Tier Pokémon can still serve as gym defenders, but they are generally easier to defeat or lack optimal defensive stats. They may perform well in niche matchups or for variety in gyms.",
  color: "bg-blue-400",
  pokemon: [
    { id: 76, name: "Shadow Alolan Golem", types: ["rock", "electric"] },
    { id: 531, name: "Audino", types: ["normal"] },
    { id: 637, name: "Volcarona", types: ["bug", "fire"] },
    { id: 748, name: "Toxapex", types: ["poison", "water"] },
    { id: 711, name: "Gourgeist (Large Size)", types: ["ghost", "grass"] },
    { id: 160, name: "Feraligatr", types: ["water"] },
    { id: 205, name: "Forretress", types: ["bug", "steel"] },
    { id: 186, name: "Politoed", types: ["water"] },
    { id: 730, name: "Primarina", types: ["water", "fairy"] },
    { id: 916, name: "Oinkologne", types: ["normal"] },
    { id: 752, name: "Araquanid", types: ["water", "bug"] },
    { id: 497, name: "Serperior", types: ["grass"] },
    { id: 697, name: "Tyrantrum", types: ["rock", "dragon"] },
    { id: 226, name: "Mantine", types: ["water", "flying"] },
    { id: 227, name: "Skarmory", types: ["steel", "flying"] },
    { id: 534, name: "Conkeldurr", types: ["fighting"] },
    { id: 233, name: "Porygon2", types: ["normal"] },
    { id: 437, name: "Bronzong", types: ["steel", "psychic"] },
    { id: 851, name: "Centiskorch", types: ["fire", "bug"] },
    { id: 724, name: "Hisuian Decidueye", types: ["grass", "fighting"] },
    { id: 344, name: "Claydol", types: ["ground", "psychic"] },
    { id: 473, name: "Mamoswine", types: ["ice", "ground"] },
    { id: 842, name: "Appletun", types: ["grass", "dragon"] },
    { id: 28, name: "Alolan Sandslash", types: ["ice", "steel"] },
    { id: 28, name: "Shadow Alolan Sandslash", types: ["ice", "steel"] },
    { id: 565, name: "Carracosta", types: ["water", "rock"] },
    { id: 462, name: "Magnezone", types: ["electric", "steel"] },
    { id: 576, name: "Gothitelle", types: ["psychic"] },
    { id: 169, name: "Crobat", types: ["poison", "flying"] },
    { id: 770, name: "Palossand", types: ["ghost", "ground"] },
    { id: 930, name: "Arboliva", types: ["grass", "normal"] },
    { id: 230, name: "Kingdra", types: ["water", "dragon"] },
    { id: 164, name: "Noctowl", types: ["normal", "flying"] },
    { id: 91, name: "Cloyster", types: ["water", "ice"] },
    { id: 36, name: "Clefable", types: ["fairy"] },
    { id: 181, name: "Ampharos", types: ["electric"] },
    { id: 537, name: "Seismitoad", types: ["water", "ground"] },
    { id: 324, name: "Torkoal", types: ["fire"] },
    { id: 553, name: "Krookodile", types: ["ground", "dark"] },
    { id: 340, name: "Whiscash", types: ["water", "ground"] },
    { id: 171, name: "Lanturn", types: ["water", "electric"] },
    { id: 214, name: "Heracross", types: ["bug", "fighting"] },
    { id: 866, name: "Mr. Rime", types: ["ice", "psychic"] },
    { id: 503, name: "Samurott", types: ["water"] },
    { id: 683, name: "Aromatisse", types: ["fairy"] },
    { id: 904, name: "Overqwil", types: ["dark", "poison"] },
    { id: 691, name: "Dragalge", types: ["poison", "dragon"] },
    { id: 80, name: "Galarian Slowbro", types: ["poison", "psychic"] },
    { id: 182, name: "Bellossom", types: ["grass"] },
    { id: 601, name: "Klinklang", types: ["steel"] },
    { id: 899, name: "Wyrdeer", types: ["normal", "psychic"] },
    { id: 470, name: "Leafeon", types: ["grass"] },
    { id: 157, name: "Hisuian Typhlosion", types: ["fire", "ghost"] },
    { id: 196, name: "Espeon", types: ["psychic"] },
    { id: 618, name: "Stunfisk", types: ["ground", "electric"] },
    { id: 99, name: "Kingler", types: ["water"] },
    { id: 213, name: "Shuckle", types: ["bug", "rock"] },
    { id: 136, name: "Flareon", types: ["fire"] },
    { id: 471, name: "Glaceon", types: ["ice"] },
    { id: 700, name: "Sylveon", types: ["fairy"] },
    { id: 901, name: "Ursaluna", types: ["ground", "normal"] },
  ],
},
D: {
  name: "D Tier",
  description:
    "D Tier Pokémon are the weakest defenders. While some may have bulk or nostalgia value, they are generally ineffective in gym defense and can be easily countered by most attackers.",
  color: "bg-blue-300",
  pokemon: [
    { id: 221, name: "Piloswine", types: ["ice", "ground"] },
    { id: 815, name: "Gigantamax Cinderace", types: ["fire"] },
    { id: 815, name: "Cinderace", types: ["fire"] },
    { id: 195, name: "Quagsire", types: ["water", "ground"] },
    { id: 781, name: "Dhelmise", types: ["ghost", "grass"] },
    { id: 55, name: "Golduck", types: ["water"] },
    { id: 362, name: "Glalie", types: ["ice"] },
    { id: 358, name: "Chimecho", types: ["psychic"] },
    { id: 500, name: "Emboar", types: ["fire", "fighting"] },
    { id: 305, name: "Lairon", types: ["steel", "rock"] },
    { id: 660, name: "Diggersby", types: ["normal", "ground"] },
    { id: 780, name: "Drampa", types: ["normal", "dragon"] },
    { id: 709, name: "Trevenant", types: ["ghost", "grass"] },
    { id: 157, name: "Hisuian Typhlosion", types: ["fire", "ghost"] },
    { id: 435, name: "Skuntank", types: ["poison", "dark"] },
    { id: 185, name: "Sudowoodo", types: ["rock"] },
    { id: 45, name: "Vileplume", types: ["grass", "poison"] },
    { id: 676, name: "Furfrou", types: ["normal"] },
    { id: 127, name: "Pinsir", types: ["bug"] },
    { id: 135, name: "Jolteon", types: ["electric"] },
    { id: 405, name: "Luxray", types: ["electric"] },
    { id: 962, name: "Bombirdier", types: ["flying", "dark"] },
    { id: 466, name: "Electivire", types: ["electric"] },
    { id: 606, name: "Beheeyem", types: ["psychic"] },
    { id: 461, name: "Weavile", types: ["dark", "ice"] },
    { id: 561, name: "Sigilyph", types: ["psychic", "flying"] },
    { id: 740, name: "Crabominable", types: ["fighting", "ice"] },
    { id: 142, name: "Aerodactyl", types: ["rock", "flying"] },
    { id: 321, name: "Wailord", types: ["water"] },
    { id: 604, name: "Eelektross", types: ["electric"] },
    { id: 745, name: "Lycanroc (Midnight Form)", types: ["rock"] },
    { id: 18, name: "Pidgeot", types: ["normal", "flying"] },
    { id: 903, name: "Sneasler", types: ["fighting", "poison"] },
    { id: 479, name: "Rotom (Frost)", types: ["electric", "ice"] },
    { id: 479, name: "Rotom (Heat)", types: ["electric", "fire"] },
    { id: 479, name: "Rotom (Mow)", types: ["electric", "grass"] },
    { id: 479, name: "Rotom (Wash)", types: ["electric", "water"] },
    { id: 207, name: "Gligar", types: ["ground", "flying"] },
    { id: 707, name: "Klefki", types: ["steel", "fairy"] },
    { id: 678, name: "Meowstic", types: ["psychic"] },
    { id: 678, name: "Meowstic (Female)", types: ["psychic"] },
    { id: 764, name: "Comfey", types: ["fairy"] },
    { id: 542, name: "Leavanny", types: ["bug", "grass"] },
    { id: 217, name: "Ursaring", types: ["normal"] },
    { id: 668, name: "Pyroar", types: ["fire", "normal"] },
    { id: 668, name: "Pyroar (Female)", types: ["fire", "normal"] },
    { id: 34, name: "Nidoking", types: ["poison", "ground"] },
    { id: 693, name: "Clawitzer", types: ["water"] },
    { id: 705, name: "Sliggoo", types: ["dragon"] },
    { id: 474, name: "Porygon-Z", types: ["normal"] },
  ],
},

}
