export interface LegacyMove {
  pokemon_id: number
  pokemon_name: string
  form?: string
  fast_attack?: string
  fast_attack_type?: string
  charged_attack?: string
  charged_attack_type?: string
  obtainable_via_tm: boolean
}

export const legacyMovesData: LegacyMove[] = [
  // Gen 1 Starters
  {
    pokemon_id: 3,
    pokemon_name: "Venusaur",
    charged_attack: "Frenzy Plant",
    charged_attack_type: "Grass",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 4,
    pokemon_name: "Charmander",
    fast_attack: "Scratch",
    fast_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 5,
    pokemon_name: "Charmeleon",
    fast_attack: "Scratch",
    fast_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 6,
    pokemon_name: "Charizard",
    charged_attack: "Blast Burn",
    charged_attack_type: "Fire",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 6,
    pokemon_name: "Charizard",
    charged_attack: "Flamethrower",
    charged_attack_type: "Fire",
    obtainable_via_tm: true,
  },
  { pokemon_id: 6, pokemon_name: "Charizard", fast_attack: "Ember", fast_attack_type: "Fire", obtainable_via_tm: true },
  {
    pokemon_id: 6,
    pokemon_name: "Charizard",
    fast_attack: "Wing Attack",
    fast_attack_type: "Flying",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 6,
    pokemon_name: "Charizard",
    fast_attack: "Dragon Breath",
    fast_attack_type: "Dragon",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 9,
    pokemon_name: "Blastoise",
    charged_attack: "Hydro Cannon",
    charged_attack_type: "Water",
    obtainable_via_tm: true,
  },

  // Early Gen 1
  {
    pokemon_id: 12,
    pokemon_name: "Butterfree",
    fast_attack: "Bug Bite",
    fast_attack_type: "Bug",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 15,
    pokemon_name: "Beedrill",
    charged_attack: "Drill Run",
    charged_attack_type: "Ground",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 18,
    pokemon_name: "Pidgeot",
    fast_attack: "Wing Attack",
    fast_attack_type: "Flying",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 20,
    pokemon_name: "Raticate",
    charged_attack: "Bite",
    charged_attack_type: "Dark",
    obtainable_via_tm: false,
  },
  {
    pokemon_id: 26,
    pokemon_name: "Raichu",
    fast_attack: "Thunder Shock",
    fast_attack_type: "Electric",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 28,
    pokemon_name: "Sandslash",
    fast_attack: "Rock Slide",
    fast_attack_type: "Rock",
    obtainable_via_tm: false,
  },
  {
    pokemon_id: 31,
    pokemon_name: "Nidoqueen",
    charged_attack: "Stone Edge",
    charged_attack_type: "Rock",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 34,
    pokemon_name: "Nidoking",
    fast_attack: "Fury Cutter",
    fast_attack_type: "Bug",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 36,
    pokemon_name: "Clefable",
    charged_attack: "Pound",
    charged_attack_type: "Normal",
    obtainable_via_tm: false,
  },
  {
    pokemon_id: 38,
    pokemon_name: "Ninetales",
    fast_attack: "Ember",
    fast_attack_type: "Fire",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 40,
    pokemon_name: "Wigglytuff",
    fast_attack: "Pound",
    fast_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 45,
    pokemon_name: "Vileplume",
    charged_attack: "Moonblast",
    charged_attack_type: "Fairy",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 49,
    pokemon_name: "Venomoth",
    fast_attack: "Bug Bite",
    fast_attack_type: "Bug",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 51,
    pokemon_name: "Dugtrio",
    charged_attack: "Mud Bomb",
    charged_attack_type: "Ground",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 53,
    pokemon_name: "Persian",
    fast_attack: "Scratch",
    fast_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 55,
    pokemon_name: "Golduck",
    fast_attack: "Water Gun",
    fast_attack_type: "Water",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 57,
    pokemon_name: "Primeape",
    fast_attack: "Karate Chop",
    fast_attack_type: "Fighting",
    obtainable_via_tm: true,
  },
  { pokemon_id: 59, pokemon_name: "Arcanine", fast_attack: "Bite", fast_attack_type: "Dark", obtainable_via_tm: true },
  {
    pokemon_id: 62,
    pokemon_name: "Poliwrath",
    charged_attack: "Submission",
    charged_attack_type: "Fighting",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 65,
    pokemon_name: "Alakazam",
    fast_attack: "Psycho Cut",
    fast_attack_type: "Psychic",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 68,
    pokemon_name: "Machamp",
    fast_attack: "Karate Chop",
    fast_attack_type: "Fighting",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 71,
    pokemon_name: "Victreebel",
    charged_attack: "Acid",
    charged_attack_type: "Poison",
    obtainable_via_tm: false,
  },
  {
    pokemon_id: 73,
    pokemon_name: "Tentacruel",
    fast_attack: "Poison Jab",
    fast_attack_type: "Poison",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 76,
    pokemon_name: "Golem",
    charged_attack: "Ancient Power",
    charged_attack_type: "Rock",
    obtainable_via_tm: true,
  },
  { pokemon_id: 78, pokemon_name: "Rapidash", fast_attack: "Ember", fast_attack_type: "Fire", obtainable_via_tm: true },
  {
    pokemon_id: 80,
    pokemon_name: "Slowbro",
    charged_attack: "Scald",
    charged_attack_type: "Water",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 82,
    pokemon_name: "Magneton",
    fast_attack: "Thunder Shock",
    fast_attack_type: "Electric",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 83,
    pokemon_name: "Farfetch'd",
    fast_attack: "Cut",
    fast_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 85,
    pokemon_name: "Dodrio",
    fast_attack: "Wing Attack",
    fast_attack_type: "Flying",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 87,
    pokemon_name: "Dewgong",
    charged_attack: "Aqua Jet",
    charged_attack_type: "Water",
    obtainable_via_tm: true,
  },
  { pokemon_id: 89, pokemon_name: "Muk", fast_attack: "Lick", fast_attack_type: "Ghost", obtainable_via_tm: true },
  {
    pokemon_id: 91,
    pokemon_name: "Cloyster",
    charged_attack: "Blizzard",
    charged_attack_type: "Ice",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 94,
    pokemon_name: "Gengar",
    fast_attack: "Shadow Claw",
    fast_attack_type: "Ghost",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 94,
    pokemon_name: "Gengar",
    charged_attack: "Sludge Wave",
    charged_attack_type: "Poison",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 97,
    pokemon_name: "Hypno",
    fast_attack: "Zen Headbutt",
    fast_attack_type: "Psychic",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 99,
    pokemon_name: "Kingler",
    fast_attack: "Mud Shot",
    fast_attack_type: "Ground",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 103,
    pokemon_name: "Exeggutor",
    fast_attack: "Confusion",
    fast_attack_type: "Psychic",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 106,
    pokemon_name: "Hitmonlee",
    fast_attack: "Brick Break",
    fast_attack_type: "Fighting",
    obtainable_via_tm: false,
  },
  {
    pokemon_id: 107,
    pokemon_name: "Hitmonchan",
    fast_attack: "Brick Break",
    fast_attack_type: "Fighting",
    obtainable_via_tm: false,
  },
  {
    pokemon_id: 110,
    pokemon_name: "Weezing",
    charged_attack: "Acid",
    charged_attack_type: "Poison",
    obtainable_via_tm: false,
  },
  {
    pokemon_id: 112,
    pokemon_name: "Rhydon",
    charged_attack: "Megahorn",
    charged_attack_type: "Bug",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 113,
    pokemon_name: "Chansey",
    fast_attack: "Pound",
    fast_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 115,
    pokemon_name: "Kangaskhan",
    charged_attack: "Stomp",
    charged_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 121,
    pokemon_name: "Starmie",
    fast_attack: "Quick Attack",
    fast_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 122,
    pokemon_name: "Mr. Mime",
    fast_attack: "Confusion",
    fast_attack_type: "Psychic",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 123,
    pokemon_name: "Scyther",
    fast_attack: "Steel Wing",
    fast_attack_type: "Steel",
    obtainable_via_tm: true,
  },
  { pokemon_id: 124, pokemon_name: "Jynx", fast_attack: "Pound", fast_attack_type: "Normal", obtainable_via_tm: true },
  {
    pokemon_id: 125,
    pokemon_name: "Electabuzz",
    fast_attack: "Low Kick",
    fast_attack_type: "Fighting",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 126,
    pokemon_name: "Magmar",
    fast_attack: "Karate Chop",
    fast_attack_type: "Fighting",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 127,
    pokemon_name: "Pinsir",
    fast_attack: "Fury Cutter",
    fast_attack_type: "Bug",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 130,
    pokemon_name: "Gyarados",
    fast_attack: "Dragon Breath",
    fast_attack_type: "Dragon",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 131,
    pokemon_name: "Lapras",
    fast_attack: "Ice Shard",
    fast_attack_type: "Ice",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 131,
    pokemon_name: "Lapras",
    charged_attack: "Ice Beam",
    charged_attack_type: "Ice",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 134,
    pokemon_name: "Vaporeon",
    charged_attack: "Last Resort",
    charged_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 135,
    pokemon_name: "Jolteon",
    charged_attack: "Last Resort",
    charged_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 136,
    pokemon_name: "Flareon",
    charged_attack: "Last Resort",
    charged_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 139,
    pokemon_name: "Omastar",
    fast_attack: "Rock Throw",
    fast_attack_type: "Rock",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 141,
    pokemon_name: "Kabutops",
    fast_attack: "Fury Cutter",
    fast_attack_type: "Bug",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 143,
    pokemon_name: "Snorlax",
    charged_attack: "Body Slam",
    charged_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 144,
    pokemon_name: "Articuno",
    charged_attack: "Hurricane",
    charged_attack_type: "Flying",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 145,
    pokemon_name: "Zapdos",
    fast_attack: "Thunder Shock",
    fast_attack_type: "Electric",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 146,
    pokemon_name: "Moltres",
    fast_attack: "Ember",
    fast_attack_type: "Fire",
    obtainable_via_tm: false,
  },
  {
    pokemon_id: 149,
    pokemon_name: "Dragonite",
    fast_attack: "Dragon Breath",
    fast_attack_type: "Dragon",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 149,
    pokemon_name: "Dragonite",
    charged_attack: "Dragon Claw",
    charged_attack_type: "Dragon",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 150,
    pokemon_name: "Mewtwo",
    charged_attack: "Shadow Ball",
    charged_attack_type: "Ghost",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 150,
    pokemon_name: "Mewtwo",
    charged_attack: "Hyper Beam",
    charged_attack_type: "Normal",
    obtainable_via_tm: true,
  },

  // Gen 2 Starters
  {
    pokemon_id: 154,
    pokemon_name: "Meganium",
    charged_attack: "Frenzy Plant",
    charged_attack_type: "Grass",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 157,
    pokemon_name: "Typhlosion",
    charged_attack: "Blast Burn",
    charged_attack_type: "Fire",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 160,
    pokemon_name: "Feraligatr",
    charged_attack: "Hydro Cannon",
    charged_attack_type: "Water",
    obtainable_via_tm: true,
  },

  // Gen 2 Pokemon
  {
    pokemon_id: 169,
    pokemon_name: "Crobat",
    fast_attack: "Air Slash",
    fast_attack_type: "Flying",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 181,
    pokemon_name: "Ampharos",
    charged_attack: "Dragon Pulse",
    charged_attack_type: "Dragon",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 186,
    pokemon_name: "Politoed",
    fast_attack: "Mud Shot",
    fast_attack_type: "Ground",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 196,
    pokemon_name: "Espeon",
    charged_attack: "Last Resort",
    charged_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 197,
    pokemon_name: "Umbreon",
    charged_attack: "Last Resort",
    charged_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 208,
    pokemon_name: "Steelix",
    fast_attack: "Iron Tail",
    fast_attack_type: "Steel",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 212,
    pokemon_name: "Scizor",
    fast_attack: "Fury Cutter",
    fast_attack_type: "Bug",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 214,
    pokemon_name: "Heracross",
    fast_attack: "Bug Bite",
    fast_attack_type: "Bug",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 229,
    pokemon_name: "Houndoom",
    charged_attack: "Flamethrower",
    charged_attack_type: "Fire",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 230,
    pokemon_name: "Kingdra",
    fast_attack: "Water Gun",
    fast_attack_type: "Water",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 233,
    pokemon_name: "Porygon2",
    charged_attack: "Tri Attack",
    charged_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 237,
    pokemon_name: "Hitmontop",
    fast_attack: "Counter",
    fast_attack_type: "Fighting",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 242,
    pokemon_name: "Blissey",
    fast_attack: "Pound",
    fast_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 248,
    pokemon_name: "Tyranitar",
    charged_attack: "Smack Down",
    charged_attack_type: "Rock",
    obtainable_via_tm: true,
  },

  // Gen 3 Starters
  {
    pokemon_id: 254,
    pokemon_name: "Sceptile",
    charged_attack: "Frenzy Plant",
    charged_attack_type: "Grass",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 257,
    pokemon_name: "Blaziken",
    charged_attack: "Blast Burn",
    charged_attack_type: "Fire",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 260,
    pokemon_name: "Swampert",
    charged_attack: "Hydro Cannon",
    charged_attack_type: "Water",
    obtainable_via_tm: true,
  },

  // Gen 3 Pokemon
  {
    pokemon_id: 282,
    pokemon_name: "Gardevoir",
    charged_attack: "Synchronoise",
    charged_attack_type: "Psychic",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 306,
    pokemon_name: "Aggron",
    charged_attack: "Heavy Slam",
    charged_attack_type: "Steel",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 319,
    pokemon_name: "Sharpedo",
    fast_attack: "Bite",
    fast_attack_type: "Dark",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 330,
    pokemon_name: "Flygon",
    fast_attack: "Earth Power",
    fast_attack_type: "Ground",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 334,
    pokemon_name: "Altaria",
    charged_attack: "Moonblast",
    charged_attack_type: "Fairy",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 350,
    pokemon_name: "Milotic",
    fast_attack: "Water Gun",
    fast_attack_type: "Water",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 376,
    pokemon_name: "Metagross",
    charged_attack: "Meteor Mash",
    charged_attack_type: "Steel",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 380,
    pokemon_name: "Latias",
    fast_attack: "Charm",
    fast_attack_type: "Fairy",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 381,
    pokemon_name: "Latios",
    fast_attack: "Dragon Breath",
    fast_attack_type: "Dragon",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 382,
    pokemon_name: "Kyogre",
    fast_attack: "Origin Pulse",
    fast_attack_type: "Water",
    obtainable_via_tm: false,
  },
  {
    pokemon_id: 383,
    pokemon_name: "Groudon",
    charged_attack: "Precipice Blades",
    charged_attack_type: "Ground",
    obtainable_via_tm: false,
  },
  {
    pokemon_id: 384,
    pokemon_name: "Rayquaza",
    fast_attack: "Dragon Ascent",
    fast_attack_type: "Flying",
    obtainable_via_tm: false,
  },

  // Gen 4 Starters
  {
    pokemon_id: 389,
    pokemon_name: "Torterra",
    charged_attack: "Frenzy Plant",
    charged_attack_type: "Grass",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 392,
    pokemon_name: "Infernape",
    charged_attack: "Blast Burn",
    charged_attack_type: "Fire",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 395,
    pokemon_name: "Empoleon",
    charged_attack: "Hydro Cannon",
    charged_attack_type: "Water",
    obtainable_via_tm: true,
  },

  // Gen 4 Pokemon
  {
    pokemon_id: 407,
    pokemon_name: "Roserade",
    charged_attack: "Weather Ball",
    charged_attack_type: "Fire",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 445,
    pokemon_name: "Garchomp",
    charged_attack: "Earth Power",
    charged_attack_type: "Ground",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 448,
    pokemon_name: "Lucario",
    charged_attack: "Aura Sphere",
    charged_attack_type: "Fighting",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 460,
    pokemon_name: "Abomasnow",
    charged_attack: "Weather Ball",
    charged_attack_type: "Ice",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 462,
    pokemon_name: "Magnezone",
    fast_attack: "Spark",
    fast_attack_type: "Electric",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 470,
    pokemon_name: "Leafeon",
    charged_attack: "Last Resort",
    charged_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 471,
    pokemon_name: "Glaceon",
    charged_attack: "Last Resort",
    charged_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 475,
    pokemon_name: "Gallade",
    charged_attack: "Synchronoise",
    charged_attack_type: "Psychic",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 483,
    pokemon_name: "Dialga",
    charged_attack: "Roar of Time",
    charged_attack_type: "Dragon",
    obtainable_via_tm: false,
  },
  {
    pokemon_id: 484,
    pokemon_name: "Palkia",
    charged_attack: "Spacial Rend",
    charged_attack_type: "Dragon",
    obtainable_via_tm: false,
  },
  {
    pokemon_id: 487,
    pokemon_name: "Giratina",
    form: "Origin",
    charged_attack: "Shadow Force",
    charged_attack_type: "Ghost",
    obtainable_via_tm: false,
  },

  // Gen 5 Starters
  {
    pokemon_id: 497,
    pokemon_name: "Serperior",
    charged_attack: "Frenzy Plant",
    charged_attack_type: "Grass",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 500,
    pokemon_name: "Emboar",
    charged_attack: "Blast Burn",
    charged_attack_type: "Fire",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 503,
    pokemon_name: "Samurott",
    charged_attack: "Hydro Cannon",
    charged_attack_type: "Water",
    obtainable_via_tm: true,
  },

  // Gen 5 Pokemon
  {
    pokemon_id: 530,
    pokemon_name: "Excadrill",
    fast_attack: "Mud-Slap",
    fast_attack_type: "Ground",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 537,
    pokemon_name: "Seismitoad",
    fast_attack: "Mud Shot",
    fast_attack_type: "Ground",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 545,
    pokemon_name: "Scolipede",
    fast_attack: "Bug Bite",
    fast_attack_type: "Bug",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 553,
    pokemon_name: "Krookodile",
    charged_attack: "Earthquake",
    charged_attack_type: "Ground",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 567,
    pokemon_name: "Archeops",
    fast_attack: "Wing Attack",
    fast_attack_type: "Flying",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 609,
    pokemon_name: "Chandelure",
    charged_attack: "Poltergeist",
    charged_attack_type: "Ghost",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 612,
    pokemon_name: "Haxorus",
    charged_attack: "Breaking Swipe",
    charged_attack_type: "Dragon",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 635,
    pokemon_name: "Hydreigon",
    charged_attack: "Brutal Swing",
    charged_attack_type: "Dark",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 643,
    pokemon_name: "Reshiram",
    charged_attack: "Fusion Flare",
    charged_attack_type: "Fire",
    obtainable_via_tm: false,
  },
  {
    pokemon_id: 644,
    pokemon_name: "Zekrom",
    charged_attack: "Fusion Bolt",
    charged_attack_type: "Electric",
    obtainable_via_tm: false,
  },

  // Gen 6 Starters
  {
    pokemon_id: 652,
    pokemon_name: "Chesnaught",
    charged_attack: "Frenzy Plant",
    charged_attack_type: "Grass",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 655,
    pokemon_name: "Delphox",
    charged_attack: "Blast Burn",
    charged_attack_type: "Fire",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 658,
    pokemon_name: "Greninja",
    charged_attack: "Hydro Cannon",
    charged_attack_type: "Water",
    obtainable_via_tm: true,
  },

  // Gen 6 Pokemon
  {
    pokemon_id: 663,
    pokemon_name: "Talonflame",
    fast_attack: "Incinerate",
    fast_attack_type: "Fire",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 700,
    pokemon_name: "Sylveon",
    charged_attack: "Last Resort",
    charged_attack_type: "Normal",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 706,
    pokemon_name: "Goodra",
    charged_attack: "Muddy Water",
    charged_attack_type: "Water",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 717,
    pokemon_name: "Yveltal",
    charged_attack: "Oblivion Wing",
    charged_attack_type: "Flying",
    obtainable_via_tm: false,
  },

  // Gen 7 Starters
  {
    pokemon_id: 724,
    pokemon_name: "Decidueye",
    charged_attack: "Frenzy Plant",
    charged_attack_type: "Grass",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 727,
    pokemon_name: "Incineroar",
    charged_attack: "Blast Burn",
    charged_attack_type: "Fire",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 730,
    pokemon_name: "Primarina",
    charged_attack: "Hydro Cannon",
    charged_attack_type: "Water",
    obtainable_via_tm: true,
  },

  // Gen 7 Pokemon
  {
    pokemon_id: 745,
    pokemon_name: "Lycanroc",
    form: "Midday",
    charged_attack: "Rock Wrecker",
    charged_attack_type: "Rock",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 778,
    pokemon_name: "Mimikyu",
    fast_attack: "Shadow Claw",
    fast_attack_type: "Ghost",
    obtainable_via_tm: true,
  },

  // Gen 8 Starters
  {
    pokemon_id: 812,
    pokemon_name: "Rillaboom",
    charged_attack: "Frenzy Plant",
    charged_attack_type: "Grass",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 815,
    pokemon_name: "Cinderace",
    charged_attack: "Blast Burn",
    charged_attack_type: "Fire",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 818,
    pokemon_name: "Inteleon",
    charged_attack: "Hydro Cannon",
    charged_attack_type: "Water",
    obtainable_via_tm: true,
  },

  // Gen 8 Pokemon
  {
    pokemon_id: 823,
    pokemon_name: "Corviknight",
    fast_attack: "Steel Wing",
    fast_attack_type: "Steel",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 826,
    pokemon_name: "Orbeetle",
    charged_attack: "Lunge",
    charged_attack_type: "Bug",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 839,
    pokemon_name: "Coalossal",
    charged_attack: "Meteor Beam",
    charged_attack_type: "Rock",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 887,
    pokemon_name: "Dragapult",
    fast_attack: "Dragon Tail",
    fast_attack_type: "Dragon",
    obtainable_via_tm: true,
  },
  {
    pokemon_id: 888,
    pokemon_name: "Zacian",
    charged_attack: "Behemoth Blade",
    charged_attack_type: "Steel",
    obtainable_via_tm: false,
  },
  {
    pokemon_id: 889,
    pokemon_name: "Zamazenta",
    charged_attack: "Behemoth Bash",
    charged_attack_type: "Fighting",
    obtainable_via_tm: false,
  },
]
